Array ( 
	[buyer_accepts_marketing] => 1
	[cancel_reason] => customer
	[cancelled_at] => 2014-03-14T16:14:06-04:00
	[cart_token] =>
	[checkout_token] =>
	[closed_at] =>
	[confirmed] =>
	[created_at] => 2014-03-14T16:14:06-04:00
	[currency] => USD
	[email] => jon@doe.ca
	[financial_status] => voided
	[fulfillment_status] => pending
	[gateway] => bogus
	[id] => 123456
	[landing_site] =>
	[location_id] =>
	[name] => #9999
	[note] =>
	[number] => 234
	[reference] =>
	[referring_site] =>
	[source] => shopify
	[source_identifier] =>
	[source_name] => shopify
	[source_url] =>
	[subtotal_price] => 229.94
	[taxes_included] =>
	[test] => 1
	[token] =>
	[total_discounts] => 0.00
	[total_line_items_price] => 229.94
	[total_price] => 239.94
	[total_price_usd] =>
	[total_tax] => 0.00
	[total_weight] => 0
	[updated_at] => 2014-03-14T16:14:06-04:00
	[user_id] =>
	[browser_ip] =>
	[landing_site_ref] =>
	[order_number] => 1234
	[discount_codes] => Array ( )
	[note_attributes] => Array ( )
	[processing_method] =>
	[checkout_id] =>
	[tax_lines] => Array ( )
	[tags] =>


	[line_items] => Array (
		[0] => Array (
			[fulfillment_service] => manual
			[fulfillment_status] =>
			[grams] => 5000
			[id] =>
			[price] => 199.99
			[product_id] =>
			[quantity] => 1
			[requires_shipping] => 1
			[sku] => SKU2006-001
			[taxable] => 1
			[title] => Sledgehammer
			[variant_id] =>
			[variant_title] =>
			[vendor] =>
			[name] => Sledgehammer
			[variant_inventory_management] =>
			[properties] => Array ( )
			[product_exists] =>
			[tax_lines] => Array ( ) 
		)
	[1] => Array (
			[fulfillment_service] => manual
			[fulfillment_status] =>
			[grams] => 500
			[id] =>
			[price] => 29.95
			[product_id] =>
			[quantity] => 1
			[requires_shipping] => 1
			[sku] => SKU2006-020
			[taxable] => 1
			[title] => Wire Cutter
			[variant_id] =>
			[variant_title] =>
			[vendor] =>
			[name] => Wire Cutter
			[variant_inventory_management] =>
			[properties] => Array ( )
			[product_exists] =>
			[tax_lines] => Array ( ) 
		) 
	)

	[shipping_lines] => Array (
		[0] => Array (
			[code] =>
			[price] => 10.00
			[source] => shopify
			[title] => Generic Shipping
			[tax_lines] => Array ( ) 
		) 
	)
	[billing_address] => Array (
		[address1] => 123 Billing Street
		[address2] =>
		[city] => Billtown
		[company] => My Company
		[country] => United States
		[first_name] => Bob
		[last_name] => Biller
		[latitude] =>
		[longitude] =>
		[phone] => 555-555-BILL
		[province] => Kentucky
		[zip] => K2P0B0
		[name] => Bob Biller
		[country_code] => US
		[province_code] => KY 
	)
	[shipping_address] => Array (
		[address1] => 123 Shipping Street
		[address2] =>
		[city] => Shippington
		[company] => Shipping Company
		[country] => United States
		[first_name] => Steve
		[last_name] => Shipper
		[latitude] =>
		[longitude] =>
		[phone] => 555-555-SHIP
		[province] => Kentucky
		[zip] => K2P0S0
		[name] => Steve Shipper
		[country_code] => US
		[province_code] => KY 
	)
		[fulfillments] => Array ( )
	[customer] => Array (
		[accepts_marketing] =>
		[created_at] =>
		[email] => john@test.com
		[first_name] => John
		[id] =>
		[last_name] => Smith
		[last_order_id] =>
		[multipass_identifier] =>
		[note] =>
		[orders_count] => 0
		[state] => disabled
		[total_spent] => 0.00
		[updated_at] =>
		[verified_email] => 1
		[tags] =>
		[last_order_name] => 
	) 
)